import assert from 'node:assert/strict'
import test from 'node:test'
import { lingyunProfile } from '../src/profile/profiles/lingyun.ts'
import { disableProfileAi, enableProfileAi, refreshProfileAi, retryProfileAi, type AiLifecycleDependencies, type AiProfileState, type AiStateRepository } from '../src/profile/aiLifecycle.ts'
import type { BuiltKnowledgeSource, EmbeddingClient, KnowledgeRepository, KnowledgeStatus, PersistedChunkInput, StoredKnowledgeSource } from '../src/knowledge/types.ts'

const profileId='11111111-1111-4111-8111-111111111111',ownerId='owner-a'
class State implements AiStateRepository{profile:AiProfileState={id:profileId,userId:ownerId,enabled:false,status:'off',isPublished:true};transitions:string[]=[];async findOwnedProfile(userId:string){return userId===ownerId?structuredClone(this.profile):null}async updateState(id:string,userId:string,values:{enabled?:boolean;status?:AiProfileState['status'];lastIndexedAt?:string|null;lastError?:string|null}){assert.equal(id,profileId);assert.equal(userId,ownerId);Object.assign(this.profile,values);if(values.status)this.transitions.push(values.status);return structuredClone(this.profile)}}
class Knowledge implements KnowledgeRepository{profile=structuredClone({...lingyunProfile,profileId});sources:StoredKnowledgeSource[]=[];searchedIds:string[]=[];fail=false;async loadProfile(id:string){assert.equal(id,profileId);return this.profile}async listSources(){return structuredClone(this.sources)}async upsertSource(id:string,source:BuiltKnowledgeSource){assert.equal(id,profileId);if(this.fail)throw new Error('persistence');let item=this.sources.find(value=>value.sourceType===source.sourceType&&value.sourceRef===source.sourceRef);if(!item){item={id:`source-${this.sources.length}`,profileId,sourceType:source.sourceType,sourceRef:source.sourceRef,contentHash:source.contentHash,status:'active',chunks:[]};this.sources.push(item)}item.contentHash=source.contentHash;return item.id}async replaceChunks(sourceId:string,chunks:PersistedChunkInput[]){const source=this.sources.find(value=>value.id===sourceId)!;source.chunks=chunks.map((chunk,index)=>({id:`chunk-${index}`,chunkIndex:chunk.chunkIndex,contentHash:chunk.contentHash,embeddingVersion:chunk.embeddingVersion}))}async deleteSources(_id:string,ids:string[]){this.sources=this.sources.filter(value=>!ids.includes(value.id))}async getStatus():Promise<KnowledgeStatus>{return{profileId,sourceCount:this.sources.length,chunkCount:this.sources.flatMap(value=>value.chunks).length,failedSourceCount:0,lastIndexedAt:'now'}}async search(){return[]}}
class Embeddings implements EmbeddingClient{readonly version='test:1536:v1';calls=0;fail=false;async embedTexts(inputs:string[]):Promise<number[][]>{if(this.fail)throw new Error('embedding');this.calls+=inputs.length;return inputs.map(()=>[1,0])}async embedText(input:string){return(await this.embedTexts([input]))[0]}}
const setup=()=>{const state=new State(),knowledge=new Knowledge(),embeddings=new Embeddings();const dependencies:AiLifecycleDependencies={state,knowledge,embeddings,now:()=> '2026-09-21T00:00:00Z'};return{state,knowledge,embeddings,dependencies}}

test('new profiles are off and enabling indexes exactly the trusted profile then becomes ready',async()=>{const value=setup();assert.equal(value.state.profile.status,'off');const result=await enableProfileAi(ownerId,value.dependencies);assert.deepEqual(value.state.transitions,['indexing','ready']);assert.equal(result.profile.status,'ready');assert.ok(result.sync.chunkCount>0);assert.ok(value.embeddings.calls>0)})
test('incremental refresh reuses unchanged knowledge without embedding calls',async()=>{const value=setup();await enableProfileAi(ownerId,value.dependencies);value.embeddings.calls=0;const result=await refreshProfileAi(ownerId,value.dependencies);assert.equal(result.profile.status,'ready');assert.equal(value.embeddings.calls,0);assert.ok(result.sync?.unchangedSources)})
test('visual-only profile changes do not trigger knowledge embeddings',async()=>{const value=setup();await enableProfileAi(ownerId,value.dependencies);value.embeddings.calls=0;value.knowledge.profile.avatar.centerDeadZone=72;const result=await refreshProfileAi(ownerId,value.dependencies);assert.equal(result.profile.status,'ready');assert.equal(value.embeddings.calls,0);assert.ok(result.sync?.unchangedSources)})
test('knowledge changes re-embed changed sources and remove deleted sources',async()=>{const value=setup();await enableProfileAi(ownerId,value.dependencies);value.embeddings.calls=0;value.knowledge.profile.projects[0].description='Changed verified details';value.knowledge.profile.projects.pop();const result=await refreshProfileAi(ownerId,value.dependencies);assert.ok(value.embeddings.calls>0);assert.ok((result.sync?.changedSources??0)+(result.sync?.deletedSources??0)>0)})
test('embedding failure sets failed and retry reaches ready',async()=>{const value=setup();value.embeddings.fail=true;await assert.rejects(enableProfileAi(ownerId,value.dependencies));assert.equal(value.state.profile.status,'failed');value.embeddings.fail=false;await retryProfileAi(ownerId,value.dependencies);assert.equal(value.state.profile.status,'ready')})
test('knowledge persistence failure is recoverable and does not mark AI ready',async()=>{const value=setup();value.knowledge.fail=true;await assert.rejects(enableProfileAi(ownerId,value.dependencies),/profile changes were saved/i);assert.equal(value.state.profile.enabled,true);assert.equal(value.state.profile.status,'failed');value.knowledge.fail=false;await retryProfileAi(ownerId,value.dependencies);assert.equal(value.state.profile.status,'ready')})
test('disable retains knowledge, publication, and profile data while turning AI off',async()=>{const value=setup();await enableProfileAi(ownerId,value.dependencies);const sourceCount=value.knowledge.sources.length;const result=await disableProfileAi(ownerId,value.dependencies);assert.equal(result.status,'off');assert.equal(result.enabled,false);assert.equal(result.isPublished,true);assert.equal(value.knowledge.sources.length,sourceCount)})
test('AI off refresh performs no knowledge or embedding work and non-owner cannot control lifecycle',async()=>{const value=setup();const result=await refreshProfileAi(ownerId,value.dependencies);assert.equal(result.sync,null);assert.equal(value.embeddings.calls,0);await assert.rejects(enableProfileAi('other-user',value.dependencies),/Profile not found/)})
