import { requireAuthenticatedUser } from '../auth/session.ts'
import { getOwnedProfile, loadOnboardingState } from '../profile/repository.ts'
import type { ProfileDocument } from '../profile/types.ts'
import { getCreateWorkspace, startCreateWorkspace } from '../onboarding/createWorkspaceApp.ts'
import { mountDashboardShell, type DashboardSection } from './DashboardShell.ts'
import { createAvatarPage } from '../avatar/avatarPage.ts'
import { listAvatarAssets, listAvatarJobs } from '../avatar/repository.ts'
import '../avatar/avatar.css'

const initialRoute=`${location.pathname}${location.hash}`
const user=await requireAuthenticatedUser(initialRoute)
const profile=await getOwnedProfile(user)
let state=await loadOnboardingState(profile)
const profileDocument=profile.document as ProfileDocument
const hasProfile=profileDocument?.profileId===profile.id,name=hasProfile?profileDocument.identity.preferredName:(user.email?.split('@')[0]??'Your account')
const shell=mountDashboardShell({user,name})
let activeAvatarPage:ReturnType<typeof createAvatarPage>|null=null
const overview=document.querySelector<HTMLTemplateElement>('#dashboardContentTemplate')!.content.firstElementChild!.cloneNode(true) as HTMLElement
const text=(root:ParentNode,id:string,value:string)=>{const element=root.querySelector<HTMLElement>(`#${id}`);if(element)element.textContent=value}
async function initialiseOverview(){const [avatars,jobs]=await Promise.all([listAvatarAssets(profile),listAvatarJobs(profile)]),generating=jobs.some(job=>job.status==='queued'||job.status==='generating'),ready=jobs.some(job=>job.status==='ready'),hasAvatar=Boolean(profile.active_avatar_id||state?.original_photo_path),hasCv=Boolean(state?.cv_path),published=profile.is_published,checks=[{label:'Add your CV or professional background',done:hasCv},{label:'Review your profile details',done:hasProfile},{label:'Create or choose your avatar',done:hasAvatar},{label:'Publish your profile',done:published}],completion=Math.round(checks.filter(x=>x.done).length/checks.length*100);text(overview,'welcomeTitle',`Welcome, ${name}`);text(overview,'completionPercent',String(completion));text(overview,'ringPercent',`${completion}%`);overview.querySelector<HTMLElement>('#progressBar')!.style.width=`${completion}%`;overview.querySelector<HTMLElement>('#completionRing')!.style.setProperty('--progress',`${completion*3.6}deg`);const remaining=overview.querySelector<HTMLUListElement>('#remainingItems')!;remaining.replaceChildren(...checks.filter(x=>!x.done).map(x=>{const li=document.createElement('li');li.textContent=x.label;return li}));const avatarTitle=profile.active_avatar_id?'Active generated avatar':generating?'Generating…':ready||avatars.length?'Avatar ready':state?.original_photo_path?'Original photo':'No avatar yet';text(overview,'avatarTitle',avatarTitle);text(overview,'avatarCopy',hasAvatar?'Your current avatar is connected to your profile.':'Add a portrait, then keep it natural or generate a living avatar.');text(overview,'knowledgeTitle',hasProfile?'Profile data ready':'Not set up');text(overview,'profileStatus',published?'Published':'Draft');overview.querySelector('#profileStatus')?.classList.toggle('published',published);const actions=overview.querySelector<HTMLElement>('#pageActions')!,make=(label:string,href:string)=>{const a=document.createElement('a');a.textContent=label;a.href=href;return a};if(published){text(overview,'pageTitle','Your profile is live');text(overview,'pageCopy','Recruiters can open and explore your public profile.');actions.append(make('View live ↗',`/${profile.slug}`),make('Edit','/dashboard/create'))}else{actions.append(make('Preview','/preview'));const b=document.createElement('button');b.disabled=true;b.textContent='Publish · Coming soon';b.className='disabled-action';actions.append(b)}}
await initialiseOverview()
const simpleView=(title:string,copy:string,action:string,href:string)=>{const main=document.createElement('main');main.className='dashboard-content';const card=document.createElement('section');card.className='card route-placeholder';const h=document.createElement('h1');h.textContent=title;const p=document.createElement('p');p.textContent=copy;const a=document.createElement('a');a.className='primary-action';a.href=href;a.dataset.dashboardRoute='';a.textContent=action;card.append(h,p,a);main.append(card);return main}
const pagesView=simpleView('Pages','Preview the profile recruiters will see. Publishing controls will appear here when supported.','Preview profile ↗','/preview')
async function renderRoute(){activeAvatarPage?.stop();activeAvatarPage=null;const path=location.pathname;let section:DashboardSection='dashboard',view=overview;if(path==='/dashboard/avatar'){section='avatar';state=await loadOnboardingState(profile);activeAvatarPage=createAvatarPage(profile,state);view=activeAvatarPage.view}else if(path==='/dashboard/create'||path==='/dashboard/profile'){section='profile';view=await getCreateWorkspace()}else if(path==='/dashboard/pages'){section='pages';view=pagesView}shell.content.replaceChildren(view);shell.setActive(section);if(activeAvatarPage)await activeAvatarPage.start();else if(view!==overview&&view!==pagesView)await startCreateWorkspace()}
function navigate(url:string){const target=new URL(url,location.href);history.pushState({},'',`${target.pathname}${target.search}${target.hash}`);void renderRoute()}
document.addEventListener('click',event=>{const anchor=(event.target as Element).closest<HTMLAnchorElement>('a[href^="\/dashboard"]');if(!anchor||event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const target=new URL(anchor.href);if(!target.pathname.startsWith('/dashboard'))return;event.preventDefault();navigate(`${target.pathname}${target.search}${target.hash}`)})
window.addEventListener('popstate',()=>void renderRoute())
await renderRoute()
